TEST_BIN = $(OBJ_DIR)/test$(BUILD_FPRINT).bin
CLIENT_BIN = $(OBJ_DIR)/client$(BUILD_FPRINT).bin
SERVER_BIN = $(OBJ_DIR)/server$(BUILD_FPRINT).bin

BINARIES += $(TEST_BIN)
BINARIES += $(CLIENT_BIN)
BINARIES += $(SERVER_BIN)
